services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: game-api
    container_name: game-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/tests/Unit
    networks:
      - game-api
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite

  nginx:
    image: nginx:alpine
    container_name: game-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - game-api
    depends_on:
      - app

networks:
  game-api:
    driver: bridge