services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    networks:
      - game-api
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    volumes:
      - app-volume:/var/www

  nginx:
    image: nginx:alpine
    container_name: game-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - game-api
    depends_on:
      - app

networks:
  game-api:
    driver: bridge